// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ad/get-groups': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ad/get-groups.get').default>>>>
    }
    '/api/ad/get-users-shared': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ad/get-users-shared.get').default>>>>
    }
    '/api/ad/get-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ad/get-users.get').default>>>>
    }
    '/api/ad/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ad/search.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/session': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/session.get').default>>>>
    }
    '/api/convert': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/convert').default>>>>
    }
    '/api/departments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/departments.get').default>>>>
    }
    '/api/incoming-control/_index_': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incoming-control/_index_.get').default>>>>
    }
    '/api/incoming-control/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incoming-control/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incoming-control/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incoming-control/[id].put').default>>>>
    }
    '/api/incoming-control/fieldsInfo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incoming-control/fieldsInfo.get').default>>>>
    }
    '/api/incoming-control': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incoming-control/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/incoming-control/index.post').default>>>>
    }
    '/api/lab/locations/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/locations/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/locations/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/locations/[id].put').default>>>>
    }
    '/api/lab/locations/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/locations/all.get').default>>>>
    }
    '/api/lab/locations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/locations/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/locations/index.post').default>>>>
    }
    '/api/lab/manufacturer/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/manufacturer/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/manufacturer/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/manufacturer/[id].put').default>>>>
    }
    '/api/lab/manufacturer/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/manufacturer/all.get').default>>>>
    }
    '/api/lab/manufacturer': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/manufacturer/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/manufacturer/index.post').default>>>>
    }
    '/api/lab/material/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/material/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/material/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/material/[id].put').default>>>>
    }
    '/api/lab/material/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/material/all.get').default>>>>
    }
    '/api/lab/material': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/material/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/material/index.post').default>>>>
    }
    '/api/lab/objects/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/objects/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/objects/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/objects/[id].put').default>>>>
    }
    '/api/lab/objects/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/objects/all.get').default>>>>
    }
    '/api/lab/objects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/objects/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/objects/index.post').default>>>>
    }
    '/api/lab/plp/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/plp/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/plp/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/plp/[id].put').default>>>>
    }
    '/api/lab/plp': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/plp/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lab/plp/index.post').default>>>>
    }
    '/api/test/domain-connection': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test/domain-connection.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/server/routes/_ipx').default>>>>
    }
  }
}
export {}