<script setup lang="ts">
import type { StorageItem } from '~/composables/useStorageManager'
useSeoMeta({ title: 'Space — файловое хранилище' })
const { mode, directory, query, type, page, items, total, busy, error, selected, checked, refresh, open, mutate, upload } = useStorageManager()
const operation = ref(''), name = ref(''), destination = ref(''), operationError = ref(''), saving = ref(false), notice = ref('')
const chosenFile = ref<File | null>(null), recordQuery = ref(''), recordId = ref(''), purpose = ref('extra'), preview = ref(false)
const operationPaths = ref<string[]>([]), replacePath = ref('')
interface RecordOption { id: number; samplingActNumber: string; samplingDate: string; testLocation: { name: string; testObject: { name: string } } }
const records = ref<RecordOption[]>([])
const crumbs = computed(() => directory.value.split('/').filter(Boolean).map((label,i,all) => ({ label, path: all.slice(0,i+1).join('/') })))
const allChecked = computed(() => items.value.filter(x=>!x.folder).length > 0 && items.value.filter(x=>!x.folder).every(x=>checked.value.includes(x.path)))
const downloadUrl = computed(() => selected.value?.url ? selected.value.url + '&download=1' : '')
function size(value: number | null) { return value === null ? '—' : value < 1024*1024 ? (value/1024).toFixed(1)+' КБ' : (value/1024/1024).toFixed(1)+' МБ' }
function date(value: string | null) { return value ? new Date(value).toLocaleDateString('ru-RU') : '—' }
function folder(path: string) { directory.value = path; refresh() }
function toggleAll(e: Event) { checked.value = (e.target as HTMLInputElement).checked ? items.value.filter(x=>!x.folder).map(x=>x.path) : [] }
async function searchRecords() {
  try { records.value = await $fetch<RecordOption[]>('/api/admin/files/records', { query: { q: recordQuery.value } }) }
  catch (e: any) { operationError.value = e.data?.message || 'Не удалось найти записи' }
}
function start(kind: string, paths?: string[]) {
  operation.value = kind; operationError.value = ''; name.value = kind === 'rename' ? selected.value?.name || '' : ''; destination.value = directory.value
  operationPaths.value = paths || (selected.value ? [selected.value.path] : [])
  if (kind === 'upload' || kind === 'replace') { purpose.value = 'extra'; recordId.value = ''; replacePath.value = kind === 'replace' ? selected.value?.path || '' : ''; searchRecords() }
}
function pick(e: Event) { chosenFile.value = (e.target as HTMLInputElement).files?.[0] || null; if (chosenFile.value) start('upload'); (e.target as HTMLInputElement).value = '' }
function drop(e: DragEvent) { chosenFile.value = e.dataTransfer?.files[0] || null; if (chosenFile.value) start('upload') }
async function apply() {
  saving.value = true; operationError.value = ''; notice.value = ''
  try {
    if (operation.value === 'upload' || operation.value === 'replace') {
      if (!chosenFile.value) throw new Error('Выберите файл')
      if (!replacePath.value && !recordId.value) throw new Error('Выберите запись реестра')
      await upload(chosenFile.value, recordId.value, purpose.value, replacePath.value)
    } else await mutate({ action: operation.value, paths: operationPaths.value, directory: operation.value === 'mkdir' ? directory.value : destination.value, name: name.value })
    operation.value = ''; chosenFile.value = null; notice.value = 'Операция выполнена. Связи документов обновлены.'
  } catch (e: any) { operationError.value = e.data?.message || e.message }
  finally { saving.value = false }
}
onMounted(refresh)
</script>
<template>
  <div class="storage-page">
    <header><h1>Файловое хранилище</h1><div class="tabs"><button :class="{ active: mode==='folders' }" @click="mode='folders'">Каталоги</button><button :class="{ active: mode==='documents' }" @click="mode='documents'">Документы</button><button @click="refresh" :disabled="busy">Обновить</button></div></header>
    <p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p>
    <div class="storage-grid"><main>
      <nav v-if="mode==='folders'" class="breadcrumbs" aria-label="Путь в хранилище"><button @click="folder('')"><Icon name="lucide:folder-open" /> Хранилище</button><template v-for="c in crumbs" :key="c.path"><span>/</span><button @click="folder(c.path)">{{ c.label }}</button></template></nav>
      <form v-else class="search" @submit.prevent="page=1;refresh()"><input v-model="query" placeholder="Номер, объект, место или ID записи" aria-label="Поиск документов"><select v-model="type" aria-label="Тип документа"><option value="">Все типы</option><option>Акт отбора</option><option>Документ о качестве</option><option>Протокол испытаний</option><option>Дополнительное вложение</option><option>Архивный документ</option></select><button type="submit">Найти</button></form>
      <p v-if="busy" role="status">Загрузка…</p>
      <div class="table-wrap"><table><thead><tr><th class="check"><input type="checkbox" :checked="allChecked" @change="toggleAll" aria-label="Выбрать все файлы"></th><th>{{ mode==='folders'?'Название':'Документ' }}</th><th>Дата</th><th>Размер</th></tr></thead><tbody><tr v-for="item in items" :key="item.path" :class="{ chosen: selected?.path===item.path }"><td><input v-if="!item.folder" type="checkbox" v-model="checked" :value="item.path" :aria-label="'Выбрать '+item.name"></td><td><button class="entry" @click="open(item)"><Icon :name="item.folder?'lucide:folder':'lucide:file-text'" :class="{ folder: item.folder }"/><span>{{ mode==='documents' && item.references[0] ? item.references[0].type+' № '+item.references[0].number : item.name }}<small v-if="!item.folder">{{ item.references.length ? 'Связей с БД: '+item.references.length : 'Без найденной связи с БД' }}<span v-if="item.state!=='present'"> · {{ item.state==='missing'?'Файл отсутствует':'Недоступен' }}</span></small></span></button></td><td>{{ date(mode==='documents' ? item.references[0]?.date || item.modified : item.modified) }}</td><td>{{ size(item.size) }}</td></tr></tbody></table></div>
      <p v-if="!busy&&!items.length">{{ mode==='folders'?'Каталог пуст':'Документы не найдены' }}</p>
      <div v-if="mode==='documents'" class="pagination"><button :disabled="page===1||busy" @click="page--;refresh()">Назад</button><span>Страница {{ page }} · найдено {{ total }}</span><button :disabled="page*100>=total||busy" @click="page++;refresh()">Далее</button></div>
    </main><aside><template v-if="selected"><h2>{{ selected.references[0]?.type || 'Файл' }}</h2><p class="filename">{{ selected.name }}</p><dl><dt>Состояние</dt><dd>{{ selected.state==='present'?'Файл доступен':selected.state==='missing'?'Файл отсутствует':'Проверка недоступна' }}</dd><dt>Размер</dt><dd>{{ size(selected.size) }}</dd><dt>Каталог</dt><dd>{{ selected.path }}</dd></dl><div v-for="ref in selected.references" :key="ref.model+ref.id+ref.field" class="reference"><strong>{{ ref.type }} № {{ ref.number }}</strong><p>{{ ref.object }}<br>{{ ref.location }}<br>Дата документа: {{ date(ref.date) }}</p><small v-if="ref.deleted">Запись помечена удалённой</small><NuxtLink v-if="ref.samplingId" :to="{ path:'/departments/lab',query:{ storageRecordId: ref.samplingId } }">К записи № {{ ref.samplingId }} →</NuxtLink></div><div class="actions"><button :disabled="selected.state!=='present'" @click="preview=true">Просмотр</button><a v-if="selected.state==='present'" :href="downloadUrl">Скачать</a><button :disabled="selected.state!=='present'" @click="start('rename')">Переименовать</button><button :disabled="selected.state!=='present'" @click="start('move')">Переместить</button><button :disabled="!selected.references.length||selected.state!=='present'" @click="chosenFile=null;start('replace')">Заменить</button><button :disabled="selected.state!=='present'" @click="start('delete')">Удалить</button></div></template><p v-else>Выберите файл, чтобы увидеть сведения и связанные записи.</p></aside></div>
    <footer><label class="drop" @dragover.prevent @drop.prevent="drop"><Icon name="lucide:upload"/> Выберите файл или перетащите его сюда<input type="file" accept=".pdf,.jpg,.jpeg,.png,.xlsx" @change="pick"><small>До 50 МБ · загрузка с привязкой к записи</small></label><button :disabled="mode!=='folders'" @click="start('mkdir')">Новая папка</button><button :disabled="!checked.length" @click="start('delete', [...checked])">Удалить выбранное ({{ checked.length }})</button></footer>
    <div v-if="operation" class="overlay"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="storage-operation-title"><h2 id="storage-operation-title">{{ ({ mkdir:'Новая папка',rename:'Переименование',move:'Перемещение',delete:'Удаление файлов',upload:'Загрузка документа',replace:'Замена документа' } as Record<string,string>)[operation] }}</h2>
      <template v-if="operation==='delete'"><p>Будут удалены {{ operationPaths.length }} файл(а) и очищены ссылки во всех связанных записях. Записи реестра сохранятся.</p><ul><li v-for="p in operationPaths" :key="p">{{ p }}</li></ul></template>
      <label v-if="operation==='mkdir'||operation==='rename'">Название<input v-model="name" required></label>
      <label v-if="operation==='move'">Каталог назначения<input v-model="destination" placeholder="lab/…"></label>
      <template v-if="operation==='upload'||operation==='replace'"><label>Файл<input type="file" accept=".pdf,.jpg,.jpeg,.png,.xlsx" @change="chosenFile=($event.target as HTMLInputElement).files?.[0]||null"></label><p>{{ chosenFile?.name }}</p><template v-if="operation==='upload'"><form class="search" @submit.prevent="searchRecords"><input v-model="recordQuery" placeholder="Номер акта или ID записи"><button>Найти запись</button></form><label>Запись реестра<select v-model="recordId"><option value="">Выберите запись</option><option v-for="r in records" :key="r.id" :value="String(r.id)">№ {{ r.id }} · {{ r.samplingActNumber }} · {{ r.testLocation.testObject.name }}</option></select></label><label>Назначение<select v-model="purpose"><option value="extra">Дополнительное вложение</option><option value="sampling">Акт отбора</option><option value="quality">Документ о качестве</option><option value="protocol">Протокол испытаний</option></select></label></template><p v-else>Новый файл заменит выбранный документ во всех связанных записях.</p></template>
      <p v-if="['rename','move'].includes(operation)">Связанные пути в БД будут обновлены. К имени добавляется уникальный идентификатор.</p><p class="error" v-if="operationError" role="alert">{{ operationError }}</p><div class="actions"><button :disabled="saving" @click="apply">{{ saving?'Выполняется…':'Подтвердить' }}</button><button :disabled="saving" @click="operation=''">Отмена</button></div></section></div>
    <div v-if="preview&&selected" class="overlay"><section class="dialog preview" role="dialog" aria-modal="true" aria-label="Просмотр документа"><button @click="preview=false">Закрыть</button><iframe v-if="/\.(pdf|png|jpe?g)$/i.test(selected.path)" :src="selected.url" title="Документ"></iframe><p v-else>Для этого формата доступно скачивание. <a :href="downloadUrl">Скачать файл</a></p></section></div>
  </div>
</template>
<style scoped>
.storage-page{padding:22px;color:#243449;background:#f5f8fc;min-height:100%}h1{font-size:25px;margin:0 0 16px}h2{font-size:17px;margin:0 0 12px}button,input,select{font:inherit;border:1px solid #d8e1ec;border-radius:6px;background:#fff;color:inherit;padding:8px 10px}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}button.active{background:#e4f0ff;border-color:#86addb}.tabs,.actions,.search,.pagination{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.storage-grid{display:grid;grid-template-columns:minmax(0,1fr) 290px;background:#fff;border:1px solid #d8e1ec;border-radius:8px;margin-top:16px;overflow:hidden}main{padding:18px;min-width:0}aside{padding:18px;background:#f8fafc;border-left:1px solid #d8e1ec;min-width:0}.breadcrumbs{display:flex;gap:5px;align-items:center;flex-wrap:wrap;margin-bottom:16px}.search{margin-bottom:16px}.search input{flex:1;min-width:140px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}td,th{padding:11px 8px;border-bottom:1px solid #e4eaf2;text-align:left}th{font-weight:500;color:#62738a}.check{width:32px}.entry{display:flex;align-items:center;gap:10px;text-align:left;border:0;padding:0;background:transparent;overflow-wrap:anywhere}.entry .folder{color:#bd9400}.entry small{display:block;color:#667a92}.chosen{background:#eaf3ff}.filename,dd,li{overflow-wrap:anywhere}dt{color:#667a92;font-size:12px;margin-top:10px}dd{margin:3px 0}.reference{border-top:1px solid #d8e1ec;margin-top:14px;padding-top:12px}.reference p{font-size:13px}.reference a{display:block;margin:8px 0}a{color:#096eb1}footer{display:flex;gap:12px;flex-wrap:wrap;align-items:center;padding:16px;margin-top:14px;background:#fff;border:1px solid #d8e1ec;border-radius:8px}.drop{flex:1;border:1px dashed #aabbd1;padding:14px;min-width:220px}.drop input{display:block;max-width:100%;margin:8px 0}.drop small{display:block;color:#667a92}.error{color:#b42318}.overlay{position:fixed;inset:0;background:#172b4d80;z-index:1100;display:flex;align-items:center;justify-content:center;padding:20px}.dialog{background:#fff;border-radius:12px;width:min(640px,100%);max-height:90vh;overflow:auto;padding:24px;color:#243449}.dialog label{display:block;margin:12px 0}.dialog label input,.dialog label select{display:block;width:100%;margin-top:5px}.preview{width:min(1100px,100%)}iframe{border:0;width:100%;height:70vh;display:block;margin-top:12px}.pagination{margin-top:16px}@media(max-width:800px){.storage-grid{grid-template-columns:1fr}aside{border-left:0;border-top:1px solid #d8e1ec}.storage-page{padding:12px}}:global(.dark-mode) .storage-page{background:#152030;color:#e5edf5}:global(.dark-mode) .storage-grid,:global(.dark-mode) footer,:global(.dark-mode) button,:global(.dark-mode) input,:global(.dark-mode) select,:global(.dark-mode) .dialog{background:#1e2c3e;color:#e5edf5;border-color:#405067}:global(.dark-mode) aside{background:#1a2738;border-color:#405067}:global(.dark-mode) .chosen,:global(.dark-mode) button.active{background:#294767}
</style>
